"""DuckDB connection + schema bootstrap + idempotent upserts (M0).

Single-writer, offline batch (PRD §5.2). The DB file lives under data/ and is
gitignored — it is derived, regenerated by `make ingest`/`make compute`.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[1]
DB_PATH = REPO_ROOT / "data" / "tickertide.duckdb"
SCHEMA_SQL = REPO_ROOT / "ingest" / "schema.sql"


def connect(path: str | Path = DB_PATH) -> duckdb.DuckDBPyConnection:
    """Open (creating if needed) the DuckDB file and apply the M0 schema."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(path))
    con.execute(SCHEMA_SQL.read_text())
    return con


def upsert_universe(con: duckdb.DuckDBPyConnection, rows: Iterable[dict], today: str) -> int:
    """INSERT OR REPLACE universe rows. `today` (ISO date) sets first_seen/last_seen."""
    payload = [
        (
            r["ticker"], r.get("name"), r.get("exchange"), r.get("sector"),
            r.get("industry"), r.get("country"), r.get("mktcap"), today, today,
        )
        for r in rows if r.get("ticker")
    ]
    if not payload:
        return 0
    # Preserve first_seen on conflict; refresh last_seen + mutable fields.
    con.executemany(
        """
        INSERT INTO universe
          (ticker, name, exchange, sector, industry, country, mktcap, first_seen, last_seen)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (ticker) DO UPDATE SET
          name=excluded.name, exchange=excluded.exchange, sector=excluded.sector,
          industry=excluded.industry, country=excluded.country, mktcap=excluded.mktcap,
          last_seen=excluded.last_seen
        """,
        payload,
    )
    return len(payload)


def upsert_bars(con: duckdb.DuckDBPyConnection, ticker: str, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE daily bars. Each bar = (date, open, high, low, close, adj_close, volume)."""
    if not bars:
        return 0
    payload = [(ticker, *b) for b in bars]
    con.executemany(
        "INSERT OR REPLACE INTO daily_bars VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        payload,
    )
    return len(payload)


def upsert_splits(con: duckdb.DuckDBPyConnection, ticker: str, rows: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE split events. Each row = (ex_date, ratio). ratio = shares-out
    multiplier on/after ex_date (forward 10-for-1 → 10.0; reverse 1-for-5 → 0.2). Feeds
    compute/valuation.py split-alignment (PRD §10.5): keeps the EDGAR per-share fundamentals
    (filing-lagged) in the SAME split basis as the yfinance price (exchange-immediate), so a
    just-split ticker's P/S, P/E, EV/S, EV/EBITDA, PEG don't collapse by the split ratio.
    Idempotent on (ticker, ex_date); split history is stable, so callers need not clear first."""
    if not rows:
        return 0
    payload = [(ticker, d, r) for (d, r) in rows]
    con.executemany("INSERT OR REPLACE INTO splits VALUES (?, ?, ?)", payload)
    return len(payload)


def clear_splits(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM splits")


def read_splits(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's split events as a pandas DataFrame (ex_date, ratio), oldest first."""
    return con.execute(
        "SELECT ex_date, ratio FROM splits WHERE ticker = ? ORDER BY ex_date", [ticker]
    ).df()


def upsert_spx(con: duckdb.DuckDBPyConnection, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE benchmark closes. Each bar = (date, ..., close, ...) -> (date, close)."""
    if not bars:
        return 0
    # bars rows are (date, open, high, low, close, adj_close, volume); take date + adj_close.
    payload = [(b[0], b[5] if len(b) > 5 and b[5] is not None else b[4]) for b in bars]
    con.executemany("INSERT OR REPLACE INTO spx_daily VALUES (?, ?)", payload)
    return len(payload)


def upsert_bucket_bars(
    con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str, rows: Sequence[Sequence]
) -> int:
    """INSERT OR REPLACE bucket (sector ETF / theme index) closes. Each row = (date, close).
    Isolated from daily_bars on purpose: bucket prices feed RS-Ratio (compute/rotation.py,
    M3.2) and must never enter the universe cross-section. `bucket` is the GICS sector
    name; `close` is total-return basis (adj_close), consistent with upsert_spx."""
    if not rows:
        return 0
    payload = [(bucket_type, bucket, d, c) for (d, c) in rows]
    con.executemany("INSERT OR REPLACE INTO bucket_bars VALUES (?, ?, ?, ?)", payload)
    return len(payload)


def clear_bucket_bars(con: duckdb.DuckDBPyConnection, bucket_type: str) -> None:
    """Delete one bucket_type's bars (e.g. 'theme' before a full theme-index rebuild),
    leaving the other type intact — sector ETF rows (M3) and theme index rows (M4) share
    the table but are rebuilt by different steps."""
    con.execute("DELETE FROM bucket_bars WHERE bucket_type = ?", [bucket_type])


def count(con: duckdb.DuckDBPyConnection, table: str) -> int:
    return con.execute(f"SELECT count(*) FROM {table}").fetchone()[0]


def distinct_bar_tickers(con: duckdb.DuckDBPyConnection) -> int:
    return con.execute("SELECT count(DISTINCT ticker) FROM daily_bars").fetchone()[0]


# --- M0.3 compute reads/writes ---

def bar_tickers(con: duckdb.DuckDBPyConnection) -> list[str]:
    """Tickers that have at least one daily bar."""
    return [r[0] for r in con.execute(
        "SELECT DISTINCT ticker FROM daily_bars ORDER BY ticker"
    ).fetchall()]


def read_bars(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's bars as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, open, high, low, close, adj_close, volume "
        "FROM daily_bars WHERE ticker = ? ORDER BY date",
        [ticker],
    ).df()


def read_spx(con: duckdb.DuckDBPyConnection):
    """Return benchmark closes as a pandas DataFrame, oldest first."""
    return con.execute("SELECT date, close FROM spx_daily ORDER BY date").df()


def clear_derived(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM derived_daily")


# base→breakout columns (PRD §10.8, 2026-06-16 spine pivot). Added to derived_daily after
# the schema froze with only ignition/composite columns → ALTER existing DBs in place
# (fresh DBs already get them from ingest/schema.sql). Idempotent: ADD COLUMN IF NOT EXISTS.
_BREAKOUT_COLS = [
    ("brk_tau_date", "VARCHAR"), ("brk_base_slope", "DOUBLE"), ("brk_brk_slope", "DOUBLE"),
    ("brk_drift_step", "DOUBLE"), ("brk_fit_gain", "DOUBLE"), ("brk_clearance", "DOUBLE"),
    ("brk_vcp", "DOUBLE"), ("brk_vsurge", "DOUBLE"), ("brk_strength", "DOUBLE"),
    ("brk_strength_pct", "DOUBLE"),
]


def ensure_breakout_columns(con: duckdb.DuckDBPyConnection) -> None:
    """Add the base→breakout columns to an existing derived_daily if missing (migration)."""
    for name, typ in _BREAKOUT_COLS:
        con.execute(f"ALTER TABLE derived_daily ADD COLUMN IF NOT EXISTS {name} {typ}")


# ignition columns retired by the 2026-06-16 spine pivot (base→breakout is the core engine).
# Drop them from an existing derived_daily so run.py's INSERT (which no longer SELECTs them)
# matches the table. Idempotent: DROP COLUMN IF EXISTS. composite/c_* stay (calc-layer, §10.6).
_IGNITION_COLS = ["ig_accel", "ig_expand", "ig_vsurge", "ig_breakout", "ig_rsturn",
                  "ignition", "ign_pct", "ign_persist_days"]


def drop_ignition_columns(con: duckdb.DuckDBPyConnection) -> None:
    """Drop the retired ignition columns from derived_daily if present (migration)."""
    for name in _IGNITION_COLS:
        con.execute(f"ALTER TABLE derived_daily DROP COLUMN IF EXISTS {name}")


# --- M0.2 fundamentals (EDGAR) ---

# Formal-filing PIT provenance (PRD §10.5). v1 ingests ONLY formal SEC filings, so every
# fundamentals_q row carries these constants; they exist as the seam for a future v2 that
# would also ingest preliminary/8-K rows (and compute a real effective_eod_date from the
# EDGAR accepted-timestamp). source_form is 'unknown' until the filing form is tracked.
SOURCE_FORMAL_FILING = "formal_filing"
SOURCE_FORM_UNKNOWN = "unknown"

# fundamentals_q columns written by upsert_fundamentals, in row order (excl. ticker). Named
# in the INSERT so physical column order (CREATE vs ALTER-appended migration) can't desync.
FUNDAMENTALS_COLS = (
    "period_end", "filed_date", "effective_eod_date", "source_type", "source_form",
    "revenue_ttm", "shares", "total_debt", "cash", "ebitda_ttm", "eps_ttm",
)


def upsert_fundamentals(con: duckdb.DuckDBPyConnection, ticker: str, rows: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE fundamentals_q. Each row carries FUNDAMENTALS_COLS in order:
    (period_end, filed_date, effective_eod_date, source_type, source_form,
     revenue_ttm, shares, total_debt, cash, ebitda_ttm, eps_ttm).
    effective_eod_date/source_type/source_form are the formal-filing PIT provenance (PRD §10.5)
    — in v1 effective_eod_date == filed_date and source_type == SOURCE_FORMAL_FILING."""
    if not rows:
        return 0
    cols = ", ".join(("ticker", *FUNDAMENTALS_COLS))
    qs = ", ".join(["?"] * (1 + len(FUNDAMENTALS_COLS)))
    payload = [(ticker, *r) for r in rows]
    con.executemany(f"INSERT OR REPLACE INTO fundamentals_q ({cols}) VALUES ({qs})", payload)
    return len(payload)


def read_fundamentals(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's trailing-4Q fundamentals as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT period_end, filed_date, effective_eod_date, source_type, source_form, "
        "revenue_ttm, shares, total_debt, cash, ebitda_ttm, eps_ttm "
        "FROM fundamentals_q WHERE ticker = ? ORDER BY period_end",
        [ticker],
    ).df()


# --- M0.4 valuation ---

def clear_valuation(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM valuation_daily")


def read_valuation(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's daily valuation multiples as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, pe, ps, evs, ev_ebitda, peg, growth, margin, rule40, "
        "as_of_period_end, as_of_filed, as_of_effective_eod, valuation_basis "
        "FROM valuation_daily WHERE ticker = ? ORDER BY date",
        [ticker],
    ).df()


# --- M3.2 rotation (bucket_bars source -> bucket_rrg RS-Ratio series) ---

def bucket_names(con: duckdb.DuckDBPyConnection, bucket_type: str = "sector") -> list[str]:
    """Distinct buckets of a type present in bucket_bars (sector ETF / theme index)."""
    return [r[0] for r in con.execute(
        "SELECT DISTINCT bucket FROM bucket_bars WHERE bucket_type = ? ORDER BY bucket",
        [bucket_type],
    ).fetchall()]


def read_bucket_bars(con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str):
    """Return one bucket's daily (date, close) as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, close FROM bucket_bars WHERE bucket_type = ? AND bucket = ? ORDER BY date",
        [bucket_type, bucket],
    ).df()


def clear_bucket_rrg(con: duckdb.DuckDBPyConnection, bucket_type: str | None = None) -> None:
    """Delete bucket_rrg rows. `bucket_type` scopes the wipe to one type so a theme
    rebuild (M4.3) leaves the sector RS-Ratio series intact (both share the table);
    None clears all (back-compat)."""
    if bucket_type is None:
        con.execute("DELETE FROM bucket_rrg")
    else:
        con.execute("DELETE FROM bucket_rrg WHERE bucket_type = ?", [bucket_type])


def upsert_bucket_rrg(
    con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str, rows: Sequence[Sequence]
) -> int:
    """INSERT OR REPLACE weekly RS-Ratio rows. Each row = (date, rs, rs_ratio)."""
    if not rows:
        return 0
    payload = [(bucket_type, bucket, d, rs, rr) for (d, rs, rr) in rows]
    con.executemany("INSERT OR REPLACE INTO bucket_rrg VALUES (?, ?, ?, ?, ?)", payload)
    return len(payload)


def read_bucket_rrg(con: duckdb.DuckDBPyConnection, bucket_type: str = "sector"):
    """Return all RS-Ratio series of a bucket_type as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT bucket, date, rs, rs_ratio FROM bucket_rrg WHERE bucket_type = ? ORDER BY bucket, date",
        [bucket_type],
    ).df()


# --- M4.1 theme membership (point-in-time; PRD §7 C3, §8.3) ---

def upsert_theme_membership(con: duckdb.DuckDBPyConnection, rows: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE theme_membership. Each row =
    (ticker, theme, exposure, as_of_date, source, approved_by). Point-in-time: a restated
    membership is a NEW row at a NEW as_of_date for the same (ticker,theme), never an
    in-place edit (C3) — REPLACE only overwrites a same-as_of correction, not history."""
    if not rows:
        return 0
    payload = [tuple(r) for r in rows]
    con.executemany(
        "INSERT OR REPLACE INTO theme_membership VALUES (?, ?, ?, ?, ?, ?)", payload
    )
    return len(payload)


def clear_theme_membership(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM theme_membership")


def theme_membership_asof(
    con: duckdb.DuckDBPyConnection,
    as_of,
    *,
    theme: str | None = None,
    ticker: str | None = None,
):
    """Point-in-time theme membership as-of `as_of` — the SINGLE source of truth for
    "who is in a theme at time t" (PRD §7 C3). Consumers: theme index (theme_index.py,
    M4.2, narrow by theme=), Stock/Discovery chips (board.py, M4.4, narrow by ticker=).

    Semantics (must not drift — fix here, not in callers):
      per (ticker, theme) take the row with the latest as_of_date <= as_of, THEN keep it
      only if exposure > 0. The exposure>0 filter is applied AFTER picking the latest row,
      so an exposure=0 restatement at date X drops the member as-of X while the pre-X
      snapshots still resolve to the old positive exposure (anti-retroactive history).

    Returns a DataFrame[ticker, theme, exposure, as_of_date, source, approved_by],
    ordered theme, exposure desc, ticker.
    """
    sql = (
        "SELECT ticker, theme, exposure, as_of_date, source, approved_by FROM ("
        "  SELECT ticker, theme, exposure, as_of_date, source, approved_by,"
        "         row_number() OVER (PARTITION BY ticker, theme ORDER BY as_of_date DESC) AS rn"
        "  FROM theme_membership WHERE as_of_date <= ?"
        ") WHERE rn = 1 AND exposure > 0"
    )
    params: list = [as_of]
    if theme is not None:
        sql += " AND theme = ?"
        params.append(theme)
    if ticker is not None:
        sql += " AND ticker = ?"
        params.append(ticker)
    sql += " ORDER BY theme, exposure DESC, ticker"
    return con.execute(sql, params).df()


def theme_keys(con: duckdb.DuckDBPyConnection) -> list[str]:
    """Distinct theme keys present in theme_membership (any as_of)."""
    return [r[0] for r in con.execute(
        "SELECT DISTINCT theme FROM theme_membership ORDER BY theme"
    ).fetchall()]
