"""DuckDB connection + schema bootstrap + idempotent upserts (M0).

Single-writer, offline batch (PRD §5.2). The DB file lives under data/ and is
gitignored — it is derived, regenerated by `make ingest`/`make compute`.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[1]
DB_PATH = REPO_ROOT / "data" / "tickertide.duckdb"
SCHEMA_SQL = REPO_ROOT / "ingest" / "schema.sql"


def connect(path: str | Path = DB_PATH) -> duckdb.DuckDBPyConnection:
    """Open (creating if needed) the DuckDB file and apply the M0 schema."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(path))
    con.execute(SCHEMA_SQL.read_text())
    return con


def upsert_universe(con: duckdb.DuckDBPyConnection, rows: Iterable[dict], today: str) -> int:
    """INSERT OR REPLACE universe rows. `today` (ISO date) sets first_seen/last_seen."""
    payload = [
        (
            r["ticker"], r.get("name"), r.get("exchange"), r.get("sector"),
            r.get("industry"), r.get("country"), r.get("mktcap"), today, today,
        )
        for r in rows if r.get("ticker")
    ]
    if not payload:
        return 0
    # Preserve first_seen on conflict; refresh last_seen + mutable fields.
    con.executemany(
        """
        INSERT INTO universe
          (ticker, name, exchange, sector, industry, country, mktcap, first_seen, last_seen)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (ticker) DO UPDATE SET
          name=excluded.name, exchange=excluded.exchange, sector=excluded.sector,
          industry=excluded.industry, country=excluded.country, mktcap=excluded.mktcap,
          last_seen=excluded.last_seen
        """,
        payload,
    )
    return len(payload)


def upsert_bars(con: duckdb.DuckDBPyConnection, ticker: str, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE daily bars. Each bar = (date, open, high, low, close, adj_close, volume)."""
    if not bars:
        return 0
    payload = [(ticker, *b) for b in bars]
    con.executemany(
        "INSERT OR REPLACE INTO daily_bars VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        payload,
    )
    return len(payload)


def upsert_spx(con: duckdb.DuckDBPyConnection, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE benchmark closes. Each bar = (date, ..., close, ...) -> (date, close)."""
    if not bars:
        return 0
    # bars rows are (date, open, high, low, close, adj_close, volume); take date + adj_close.
    payload = [(b[0], b[5] if len(b) > 5 and b[5] is not None else b[4]) for b in bars]
    con.executemany("INSERT OR REPLACE INTO spx_daily VALUES (?, ?)", payload)
    return len(payload)


def upsert_bucket_bars(
    con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str, rows: Sequence[Sequence]
) -> int:
    """INSERT OR REPLACE bucket (sector ETF / theme index) closes. Each row = (date, close).
    Isolated from daily_bars on purpose: bucket prices feed RS-Ratio (compute/rotation.py,
    M3.2) and must never enter the universe cross-section. `bucket` is the GICS sector
    name; `close` is total-return basis (adj_close), consistent with upsert_spx."""
    if not rows:
        return 0
    payload = [(bucket_type, bucket, d, c) for (d, c) in rows]
    con.executemany("INSERT OR REPLACE INTO bucket_bars VALUES (?, ?, ?, ?)", payload)
    return len(payload)


def count(con: duckdb.DuckDBPyConnection, table: str) -> int:
    return con.execute(f"SELECT count(*) FROM {table}").fetchone()[0]


def distinct_bar_tickers(con: duckdb.DuckDBPyConnection) -> int:
    return con.execute("SELECT count(DISTINCT ticker) FROM daily_bars").fetchone()[0]


# --- M0.3 compute reads/writes ---

def bar_tickers(con: duckdb.DuckDBPyConnection) -> list[str]:
    """Tickers that have at least one daily bar."""
    return [r[0] for r in con.execute(
        "SELECT DISTINCT ticker FROM daily_bars ORDER BY ticker"
    ).fetchall()]


def read_bars(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's bars as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, open, high, low, close, adj_close, volume "
        "FROM daily_bars WHERE ticker = ? ORDER BY date",
        [ticker],
    ).df()


def read_spx(con: duckdb.DuckDBPyConnection):
    """Return benchmark closes as a pandas DataFrame, oldest first."""
    return con.execute("SELECT date, close FROM spx_daily ORDER BY date").df()


def clear_derived(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM derived_daily")


# --- M0.2 fundamentals (EDGAR) ---

def upsert_fundamentals(con: duckdb.DuckDBPyConnection, ticker: str, rows: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE fundamentals_q. Each row =
    (period_end, filed_date, revenue_ttm, shares, total_debt, cash, ebitda_ttm, eps_ttm)."""
    if not rows:
        return 0
    payload = [(ticker, *r) for r in rows]
    con.executemany(
        "INSERT OR REPLACE INTO fundamentals_q VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        payload,
    )
    return len(payload)


def read_fundamentals(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's trailing-4Q fundamentals as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT period_end, filed_date, revenue_ttm, shares, total_debt, cash, ebitda_ttm, eps_ttm "
        "FROM fundamentals_q WHERE ticker = ? ORDER BY period_end",
        [ticker],
    ).df()


# --- M0.4 valuation ---

def clear_valuation(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM valuation_daily")


def read_valuation(con: duckdb.DuckDBPyConnection, ticker: str):
    """Return a ticker's daily valuation multiples as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, pe, ps, evs, ev_ebitda, peg, growth, margin, rule40, as_of_period_end, as_of_filed "
        "FROM valuation_daily WHERE ticker = ? ORDER BY date",
        [ticker],
    ).df()


# --- M3.2 rotation (bucket_bars source -> bucket_rrg RS-Ratio series) ---

def bucket_names(con: duckdb.DuckDBPyConnection, bucket_type: str = "sector") -> list[str]:
    """Distinct buckets of a type present in bucket_bars (sector ETF / theme index)."""
    return [r[0] for r in con.execute(
        "SELECT DISTINCT bucket FROM bucket_bars WHERE bucket_type = ? ORDER BY bucket",
        [bucket_type],
    ).fetchall()]


def read_bucket_bars(con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str):
    """Return one bucket's daily (date, close) as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT date, close FROM bucket_bars WHERE bucket_type = ? AND bucket = ? ORDER BY date",
        [bucket_type, bucket],
    ).df()


def clear_bucket_rrg(con: duckdb.DuckDBPyConnection) -> None:
    con.execute("DELETE FROM bucket_rrg")


def upsert_bucket_rrg(
    con: duckdb.DuckDBPyConnection, bucket_type: str, bucket: str, rows: Sequence[Sequence]
) -> int:
    """INSERT OR REPLACE weekly RS-Ratio rows. Each row = (date, rs, rs_ratio)."""
    if not rows:
        return 0
    payload = [(bucket_type, bucket, d, rs, rr) for (d, rs, rr) in rows]
    con.executemany("INSERT OR REPLACE INTO bucket_rrg VALUES (?, ?, ?, ?, ?)", payload)
    return len(payload)


def read_bucket_rrg(con: duckdb.DuckDBPyConnection, bucket_type: str = "sector"):
    """Return all RS-Ratio series of a bucket_type as a pandas DataFrame, oldest first."""
    return con.execute(
        "SELECT bucket, date, rs, rs_ratio FROM bucket_rrg WHERE bucket_type = ? ORDER BY bucket, date",
        [bucket_type],
    ).df()
