"""DuckDB connection + schema bootstrap + idempotent upserts (M0).

Single-writer, offline batch (PRD §5.2). The DB file lives under data/ and is
gitignored — it is derived, regenerated by `make ingest`/`make compute`.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[1]
DB_PATH = REPO_ROOT / "data" / "tickertide.duckdb"
SCHEMA_SQL = REPO_ROOT / "ingest" / "schema.sql"


def connect(path: str | Path = DB_PATH) -> duckdb.DuckDBPyConnection:
    """Open (creating if needed) the DuckDB file and apply the M0 schema."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(path))
    con.execute(SCHEMA_SQL.read_text())
    return con


def upsert_universe(con: duckdb.DuckDBPyConnection, rows: Iterable[dict], today: str) -> int:
    """INSERT OR REPLACE universe rows. `today` (ISO date) sets first_seen/last_seen."""
    payload = [
        (
            r["ticker"], r.get("name"), r.get("exchange"), r.get("sector"),
            r.get("industry"), r.get("country"), r.get("mktcap"), today, today,
        )
        for r in rows if r.get("ticker")
    ]
    if not payload:
        return 0
    # Preserve first_seen on conflict; refresh last_seen + mutable fields.
    con.executemany(
        """
        INSERT INTO universe
          (ticker, name, exchange, sector, industry, country, mktcap, first_seen, last_seen)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (ticker) DO UPDATE SET
          name=excluded.name, exchange=excluded.exchange, sector=excluded.sector,
          industry=excluded.industry, country=excluded.country, mktcap=excluded.mktcap,
          last_seen=excluded.last_seen
        """,
        payload,
    )
    return len(payload)


def upsert_bars(con: duckdb.DuckDBPyConnection, ticker: str, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE daily bars. Each bar = (date, open, high, low, close, adj_close, volume)."""
    if not bars:
        return 0
    payload = [(ticker, *b) for b in bars]
    con.executemany(
        "INSERT OR REPLACE INTO daily_bars VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        payload,
    )
    return len(payload)


def upsert_spx(con: duckdb.DuckDBPyConnection, bars: Sequence[Sequence]) -> int:
    """INSERT OR REPLACE benchmark closes. Each bar = (date, ..., close, ...) -> (date, close)."""
    if not bars:
        return 0
    # bars rows are (date, open, high, low, close, adj_close, volume); take date + adj_close.
    payload = [(b[0], b[5] if len(b) > 5 and b[5] is not None else b[4]) for b in bars]
    con.executemany("INSERT OR REPLACE INTO spx_daily VALUES (?, ?)", payload)
    return len(payload)


def count(con: duckdb.DuckDBPyConnection, table: str) -> int:
    return con.execute(f"SELECT count(*) FROM {table}").fetchone()[0]


def distinct_bar_tickers(con: duckdb.DuckDBPyConnection) -> int:
    return con.execute("SELECT count(DISTINCT ticker) FROM daily_bars").fetchone()[0]
